fixed Dockerfile

diff --git a/entrypoint b/entrypoint
--- a/entrypoint
+++ b/entrypoint
@@ -16,15 +16,29 @@ ENCRYPTION_SS="salsa20"
 SHADOWSOCKS="/usr/local/bin/ss-server"
 KCPTUN="/usr/go/bin/server"
 
+if [ -z "$PASSWORD_SS" ]
+then
+      echo "Error: No password set. Set \$PASSWORD_SS"
+      exit 1
+fi
 
-echo "Launching Shadowsocks server over KCP tunnel on : $BINDADDR:$PORTNUMBER_KCP"
-echo "KCP tunel mode :                                  $MODE_KCP"
-echo "KCP tunel DSCP :                                  $DSCP_KCP"
-echo "KCP tunel encryption :                            $ENCRYPTION_KCP"
-echo "Shadowsocks encryption :                          $ENCRYPTION_SS"
+if [ -z "$ENCRYPTION_KCP" ]
+then
+      echo "Warning: \$ENCRYPTION_KCP is unset."
+      exit 1
+fi
 
-echo "Launching Shadowsocks server on :                 $BINDADDR:$PORTNUMBER_NOKCP"
-echo "Shadowsocks encryption :                          $ENCRYPTION_SS"
+
+echo "[Launching Shadowsocks server over KCP tunnel.]"
+echo "KCP endpoint:                       $BINDADDR:$PORTNUMBER_KCP"
+echo "KCP tunel mode :                    $MODE_KCP"
+echo "KCP tunel DSCP :                    $DSCP_KCP"
+echo "KCP tunel encryption :              $ENCRYPTION_KCP"
+echo "Shadowsocks encryption :            $ENCRYPTION_SS"
+echo ""
+echo "[Launching Shadowsocks server.]"
+echo "Shadowsocks endpoint :              $BINDADDR:$PORTNUMBER_NOKCP"
+echo "Shadowsocks encryption :            $ENCRYPTION_SS"
 
 echo "To watch the output, run"
 echo "  docker ps -ql | xargs docker logs -f"
